### ISSUE TITLE
virus alert

### ISSUE THREAD

**Issue by blharding-water** [NLNZDigitalPreservation/bruteforce_legacy_file_converter#1]
Trend Micro detected Ransom.Win32.Trx.XXPE50FSX052 in LegacyFileConverter.exe

**Comment by jaknz** [comment]
VirusTotal seems to think it's okay, as does Windows Defender:
https://www.virustotal.com/gui/url/e041452ba8cdf5abf1f4cd167008cbbaf92dcb674c5160c92f5ab827cfe6151e?nocache=1

**Comment by blharding-water** [comment]
Thanks. It stopped it dead in the Mozilla temp folder. I think I can turn it off temporarily.  On Nov 17, 2024, at 4:28 PM, Jeremy K ***@***.***> wrote:﻿
VirusTotal seems to think it's okay, as does Windows Defender:
https://www.virustotal.com/gui/url/e041452ba8cdf5abf1f4cd167008cbbaf92dcb674c5160c92f5ab827cfe6151e?nocache=1
https://www.virustotal.com/gui/file/c02f9f93502091c4a3d0c7ea7ea9ad7ed87f4012d36503e17697d52504b04394?nocache=1
